import importlib
from PythonSE.se_engine import auto_generate_tests
from PythonSE.auto_generate_tests import generate_pytest_from_auto_tests
from z3 import (
    Int, And, Or, Not, Implies, BoolVal, IntVal, BitVec,
    Solver, sat, unsat,
)

BW=32

def main():
    program_package = "PythonSE.ExamplePrograms"
    names = ["zune_days"]
    for name in names:
        print("Generating Test Cases for Module:", name)
        m = importlib.import_module(f"{program_package}.{name}")

        fn = getattr(m, name)

        if name == "clamp_sub":
            a = BitVec("a", BW)
            b = BitVec("b", BW)
            wrapped_sub = a - b

            suspicious_overflow = Or(
                And(a >= 0, b <= 0, wrapped_sub < 0),
                And(a <= 0, b >= 0, wrapped_sub > 0),
            )

            tests = auto_generate_tests(fn, mode="dsa", extra_constraints=suspicious_overflow, max_depth=1)
        else:
            tests = auto_generate_tests(fn, mode="dsa", max_depth=1)
        for i, t in enumerate(tests):
            print(f"   Test {i}")
            print("      path constraints:",  t["pc"])
            print("      function inputs:",   t["inputs"])
            print("      symbolic return:",   t["symbolic return"])
            print("      real return:",       t["real return"])
            print()
        print()
        print()

        _ = generate_pytest_from_auto_tests(
            tests,
            package = program_package,
            module_name=name,
            function_name=name,
            output_file=f"PythonSE/AutoGeneratedUnitTests/{name}_tests.py",
        )


if __name__ == '__main__':
    main()

